// data.js
export const reviewsData = [
  {
    id: 1,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_1.png",
    name: "Sofia Harvetz",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 2,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_2.png",
    name: "Nicolas Jensen",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 3,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_3.png",
    name: "Nicolas Jensen",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 4,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_4.png",
    name: "Nicolas Jensen",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 5,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_5.png",
    name: "Nicolas Jensen",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 6,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_1.png",
    name: "Nicolas Jensen",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 7,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_1.png",
    name: "Sofia Harvetz",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 8,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_2.png",
    name: "Nicolas Jensen",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 9,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_3.png",
    name: "Nicolas Jensen",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 10,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_4.png",
    name: "Nicolas Jensen",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 11,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_5.png",
    name: "Nicolas Jensen",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 12,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_4.png",
    name: "Nicolas Jensen",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 13,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_1.png",
    name: "Sofia Harvetz",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 14,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_2.png",
    name: "Nicolas Jensen",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 15,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_3.png",
    name: "Nicolas Jensen",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 16,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_4.png",
    name: "Nicolas Jensen",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 17,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_5.png",
    name: "Nicolas Jensen",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 18,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_3.png",
    name: "Nicolas Jensen",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 19,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_1.png",
    name: "Sofia Harvetz",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 20,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_2.png",
    name: "Nicolas Jensen",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 21,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_3.png",
    name: "Nicolas Jensen",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 22,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_4.png",
    name: "Nicolas Jensen",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 23,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_5.png",
    name: "Nicolas Jensen",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
  {
    id: 24,
    ratingImg: "/src/img/product_page/rating_product.png",
    avatar: "/src/img/review_list/avatar_user_4.png",
    name: "Nicolas Jensen",
    comment:
      "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupt et quas molestias excepturi sint non provident.",
    time: "About 1 hour ago",
    isLiked: false,
    reaction: null,
  },
];